// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// arma_repmat
arma::mat arma_repmat(arma::mat A, int n, int m);
RcppExport SEXP _segtools_arma_repmat(SEXP ASEXP, SEXP nSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(arma_repmat(A, n, m));
    return rcpp_result_gen;
END_RCPP
}
// sweep_row_plus
Rcpp::NumericMatrix sweep_row_plus(Rcpp::NumericMatrix dkp, Rcpp:: NumericVector wk);
RcppExport SEXP _segtools_sweep_row_plus(SEXP dkpSEXP, SEXP wkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type dkp(dkpSEXP);
    Rcpp::traits::input_parameter< Rcpp:: NumericVector >::type wk(wkSEXP);
    rcpp_result_gen = Rcpp::wrap(sweep_row_plus(dkp, wk));
    return rcpp_result_gen;
END_RCPP
}
// sweep_col_divide
Rcpp::NumericMatrix sweep_col_divide(Rcpp::NumericMatrix A, Rcpp:: NumericVector s);
RcppExport SEXP _segtools_sweep_col_divide(SEXP ASEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp:: NumericVector >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(sweep_col_divide(A, s));
    return rcpp_result_gen;
END_RCPP
}
// sweep_col_plus
Rcpp::NumericMatrix sweep_col_plus(Rcpp::NumericMatrix A, Rcpp::NumericVector s);
RcppExport SEXP _segtools_sweep_col_plus(SEXP ASEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(sweep_col_plus(A, s));
    return rcpp_result_gen;
END_RCPP
}
// sweep_row_times
Rcpp::NumericMatrix sweep_row_times(Rcpp::NumericMatrix A, Rcpp::NumericVector s);
RcppExport SEXP _segtools_sweep_row_times(SEXP ASEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(sweep_row_times(A, s));
    return rcpp_result_gen;
END_RCPP
}
// sweep_row_times2
Rcpp::NumericMatrix sweep_row_times2(Rcpp::NumericMatrix A, Rcpp::NumericVector s);
RcppExport SEXP _segtools_sweep_row_times2(SEXP ASEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(sweep_row_times2(A, s));
    return rcpp_result_gen;
END_RCPP
}
// apply_col_max
Rcpp::NumericVector apply_col_max(Rcpp::NumericMatrix A);
RcppExport SEXP _segtools_apply_col_max(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(apply_col_max(A));
    return rcpp_result_gen;
END_RCPP
}
// apply_col_sum
Rcpp::NumericVector apply_col_sum(Rcpp::NumericMatrix A);
RcppExport SEXP _segtools_apply_col_sum(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(apply_col_sum(A));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_segtools_arma_repmat", (DL_FUNC) &_segtools_arma_repmat, 3},
    {"_segtools_sweep_row_plus", (DL_FUNC) &_segtools_sweep_row_plus, 2},
    {"_segtools_sweep_col_divide", (DL_FUNC) &_segtools_sweep_col_divide, 2},
    {"_segtools_sweep_col_plus", (DL_FUNC) &_segtools_sweep_col_plus, 2},
    {"_segtools_sweep_row_times", (DL_FUNC) &_segtools_sweep_row_times, 2},
    {"_segtools_sweep_row_times2", (DL_FUNC) &_segtools_sweep_row_times2, 2},
    {"_segtools_apply_col_max", (DL_FUNC) &_segtools_apply_col_max, 1},
    {"_segtools_apply_col_sum", (DL_FUNC) &_segtools_apply_col_sum, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_segtools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
