# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' DynProg_algo_cpp
#'
#' This function finds the best segmentation given a Cost Matrix using a
#' dynamic programming algorithm. C++ implementation of \link{DynProg}
#'
#' @param matD Cost Matrix
#' @param x An integer vector
#' @export
DynProg_algo_cpp <- function(matD, Kmax) {
    .Call('_segtools_DynProg_algo_cpp', PACKAGE = 'segtools', matD, Kmax)
}

#' logdens_simultanee_cpp
#'
#' Calculate logdensity of a bivariate signal
#'
#' @rdname logdens_simultanee
#' @param mu mean parameter for each signal
#' @param sigma standard deviation parameter for each signal
#' @param prop mixture parameter
logdens_simultanee_cpp <- function(xk, mu, sigma, prop) {
    .Call('_segtools_logdens_simultanee_cpp', PACKAGE = 'segtools', xk, mu, sigma, prop)
}

#' apply_rowSums
#'
#' Internal function for Expectation-Maximization (EM) algorithm.
#'
#' @param rupt current estimated breaks in signal
#' @param x bivariate signal
apply_rowSums <- function(rupt, x) {
    .Call('_segtools_apply_rowSums', PACKAGE = 'segtools', rupt, x)
}

#' colsums_sapply
#'
#' Internal function for Expectation-Maximization (EM) algorithm.
#'
#' @param rupt current estimated breaks in signal
#' @param x bivariate signal
#' @param mu mean parameter for each signal
#' @param tau tau
#' @param i number of signal
colsums_sapply <- function(i, rupt, x, mu, tau) {
    .Call('_segtools_colsums_sapply', PACKAGE = 'segtools', i, rupt, x, mu, tau)
}

#' arma_repmat
#'
#' C++ Armadillo version for repmat function. Repeat a matrix in bloc.
#'
#' @param A matrix
#' @param n number of repetition in line
#' @param m number of repetition in column
arma_repmat <- function(A, n, m) {
    .Call('_segtools_arma_repmat', PACKAGE = 'segtools', A, n, m)
}

#' Gmixt_algo_cpp
#'
#' Internal C++ algorithm for computing the cost matrix.
#'
#' @param A matrix
#' @param n number of repetition in line
#' @param m number of repetition in column
Gmixt_algo_cpp <- function(zi, lgi, P, mvec, wk, svec, prop) {
    .Call('_segtools_Gmixt_algo_cpp', PACKAGE = 'segtools', zi, lgi, P, mvec, wk, svec, prop)
}

#' Gmixt_simultanee_fullcpp
#'
#' C++ function replacing \link{Gmixt_simultanee}
#'
#' @param Don Bivariate Signal
#' @param lmin minimum length of segments
#' @param prop mixture parameters
#' @param mu mean parameters
#' @param s standard deviation paramaters
Gmixt_simultanee_fullcpp <- function(Don, lmin, prop, mu, s) {
    .Call('_segtools_Gmixt_simultanee_fullcpp', PACKAGE = 'segtools', Don, lmin, prop, mu, s)
}

