# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

arma_repmat <- function(A, n, m) {
    .Call('_segtools_arma_repmat', PACKAGE = 'segtools', A, n, m)
}

sweep_row_plus <- function(dkp, wk) {
    .Call('_segtools_sweep_row_plus', PACKAGE = 'segtools', dkp, wk)
}

sweep_col_divide <- function(A, s) {
    .Call('_segtools_sweep_col_divide', PACKAGE = 'segtools', A, s)
}

sweep_col_plus <- function(A, s) {
    .Call('_segtools_sweep_col_plus', PACKAGE = 'segtools', A, s)
}

sweep_row_times <- function(A, s) {
    .Call('_segtools_sweep_row_times', PACKAGE = 'segtools', A, s)
}

sweep_row_times2 <- function(A, s) {
    .Call('_segtools_sweep_row_times2', PACKAGE = 'segtools', A, s)
}

apply_col_max <- function(A) {
    .Call('_segtools_apply_col_max', PACKAGE = 'segtools', A)
}

apply_col_sum <- function(A) {
    .Call('_segtools_apply_col_sum', PACKAGE = 'segtools', A)
}

